### PR TITLE
Fix one wrong translation

### PR DESCRIPTION
**Pull request by rtxyd**

### CODE REVIEW

**Comment by Speiger** [comment]
Could you explain what it fixes?

**Comment by rtxyd** [comment]
the description of "focus impact", I have reported that issue since I realized this enchantment didn't worked with what I translated, the same time I made a further test about how attack speed influence the weapon of this enchantment.

**Comment by rtxyd** [comment]
earlier, I translated the description of "focus impact" with " increase damage but decrease attack speed", I have edited it to " increase damage of low attack speed".

**Comment by Speiger** [comment]
What about ifrits_grace?
Why was that changed?
I just need to confirm why changes are made.
(To understand the reason behind it)

**Comment by Speiger** [comment]
@rtxyd

**Comment by rtxyd** [comment]
@Speiger we call ifrit "伊芙利特"(this is the most common translation) instead of "伊弗里特", I forgot to change that since I use google translation at first. And the description of it had a grammar mistake in Chinese, I delete the mistake part.

**Comment by rtxyd** [comment]
Maybe I could explain some things about western names in Chinese translation. And because of my bad English, I could only tell like these. Some wetern names have different translations and they are right indeed, but I just want the name more common so that everyone knows. 
The following is what I as a Chinese consider about the name of "ifrit".
In this case, the character "伊芙" of "伊芙利特(yi fu li te)" looks like a feminine words,  the "利特" looks like a neutral but soft words in name, at this circumstance "伊" is a word to enchance the feminine feeling of "伊芙",  yet the "弗" and "里特" of "伊弗里特(yi fu li te)" are more masculine, at this circumstance "伊" is a neutral word. As I know, we often take "ifrit" as a female name.
And maybe I could associate like this,  "伊" as "E", "芙" as "ve", so "伊芙" is like "Eve" of "Evening". And "弗" as "var" of "havard" or "f" of "Fluorine". The rest words "利特" and "里特"  I can't describe like this. But "里特" looks more like a masculine name in Chinese.

**Comment by rtxyd** [comment]
And the grammar mistake is like this. "通过" means "with", "by",  "through", "via" or it can be a verb. I don't talk much about that. In this case, "通过用岩浆桶Shift右击铁砧给你的物品栏中的工具吃岩浆", the "通过" is a verb means "use some way to do", and "用" means "use", so you can see, "some way" at this moment is "用......"(use......), and the translation of "通过用......" is "use use...... to do.", that is a grammar mistake in Chinese, **we can't use two same "use" to use something. Because the previous ”通过“ has included the meaning of "用".**

**Comment by Speiger** [comment]
Thanks for the detailed description, which was actually quite interesting to read.
Thanks for that. You don't need to do that detailed of a explanation everytime. 
Something simple like on focus impact would be fine too. 
Merged

**Pull request merged**
