### PR TITLE
change to true translate

### PR DESCRIPTION
**Pull request by a5161655**

### CODE REVIEW

**Comment by Speiger** [comment]
@a5161655 could you explain the changes? So we understand why the changes are happening.

**Comment by a5161655** [comment]
because this guy，rtxyd like to translate with google translate and he will not to examine what is wrong.
you can see some mistake on his translation,He expressed the wrong meaning in chinese,It could be Cause difficulties for chinese player when playing this mod,I can do better than him.

**Comment by a5161655** [comment]
for example，enchantment.uniquee.arthropods=节肢动物祸根
enchantment.uniquee.arthropods.desc=节肢动物之祸的高级版本
enchantment.uniquee.vitae.desc=让您更加健康
enchantment.uniquee.climate_tranquility.desc=武器会对温度做出反应，并受到对方的影响。在特别炎热或寒冷的生物群落中，您的武器将与对立元素抵消温度。
enchantment.uniquee.momentum=动量
enchantment.uniquee.momentum.desc=持续开采同一方块将进一步提高开采速度
enchantment.uniquee.fastfood=贝尔格里斯的祝福
enchantment.uniquee.fastfood.desc=非敌对的生物将不再掉落物品，但是它们的死亡将恢复你的饥饿感。
enchantment.uniquee.ecological.desc=站在木材（原木）和树叶附近，将缓慢恢复工具的耐用性。
enchantment.uniquee.midas_blessing.desc=Shift右键单击一个砧以将金锭存储在您的工具中。开采任何类型的宝石时，您的黄金储备将被耗尽，以增加您的掉落量。
and so forth.
it's not true in chinese.

**Comment by WuzgXY-GitHub** [comment]
> @a5161655 could you explain the changes? So we understand why the changes are happening.

a5161655 just replaced the machine-translation with translation made by himself.

**Comment by rtxyd** [comment]
You could say all my translation is machine. I don't think the translation is wrong if I deliver correct meaning with the support of machine, which meaning is not offend to the intended of author. I respect the decision of author. 
And I feel like what WuzgXY thought is "Translations will stand front of every Chinese player, so we must do it with all efforts instead of with machine. "
I've played this mod for some time. Speiger is a good man who taught me to make my first translation. I will always appreciate him. And yes this is my first translation, I use translate applications like google to find a suitable translation, and sometimes look up dictionary at the condition that didn't change the original meaning of the English version. Then I may make it a little personal, memic or fun. That's it.
If you want to make another translation, then just make it ,and pull a request, explain all the changes in ways the author could understand, instead of blaming me. Everybody should be calm. 
You could say I am lazy. I confess it's true. I just check every words that machine translates to make sure if the machine did wrong. If it's wrong and I can't understand, I fix it to a version which is better to understand. If I didn't change it, it means I beleve people will understand how this enchantment works with the rough description and playing time.
During these days, I found that Speiger is a "concrete" person, every time I change my translation, I explain them detailedly. 
You need to explain why your translation is the true one. These are my insignificant experiences, I hope I could help if my version fail to make it.

**Comment by WuzgXY-GitHub** [comment]
@rtxyd I do appreciate your attitude now

**Comment by Speiger** [comment]
@a5161655 please be kind to @rtxyd. Yes he did a Machine Translation but he put in the effort of making one in the first place.
Yes it is not ideal but it was a start. A start is not "final" and I bet someone will find issues in your translation as well.
This is not a insult but try to understand my point.

Why a explanation is needed? (And we will make a template soonish to make it simpler to understand)

I don't speak Chinese. So you need to make clear to me why things are wrong or why yours is usable.
Because I can not see the mistakes that could exist in there.
If it sounds reasonable to me then I can make an easy choice vs a troubled one where I need to guess "is this a good or bad change"

To give a example: 
(Old) enchantment.uniquee.berserk.desc=您的生命值越低，伤害越高 => (The lower your health, the higher the damage)
(New) enchantment.uniquee.berserk.desc=生命值越低，伤害越高 =>(The lower the health, the higher the damage)

Old one to me makes more sense to me, that is something, if no reasoning is provided, it makes me think the new translation is inferior.

Now after I explained this I am going to merge this change because I can see there is a improvement in the translation.

Thank you for all of you putting that work into the translation.

The new Translation will be released with the next patch.

**Comment by a5161655** [comment]
I sorry about that because my word hurt him and I have a mistake in my  translation，I will fix it.
很对不起我说的话有点伤人。

**Comment by Speiger** [comment]
No Problem, we all do mistakes.

**Comment by WuzgXY-GitHub** [comment]
I’m not good at expressing emotional things that I want to say in words, especially in another language, sorry for that XD

**Pull request merged**
