### PR TITLE
Create zh_cn.lang

### PR DESCRIPTION
**Pull request by rtxyd**
I try many times, in fact, it is that I can't change the fork name.. whatever.
I am a noob, but I need this mod to play, and my friends can't read English, so that's it. If there is a more proffesional translation, this version shoud be forgoten.

### CODE REVIEW

**Comment by rtxyd** [comment]
Sorry for interrupting so many times, I just need to find a tutorial so I can use GitHub more adept.

**Comment by Speiger** [comment]
@rtxyd how to prevent making a lot of merge request.

- 1: Make a fork.
- 2: Do all change you want inside your fork.
- 3: Make a pullrequest with your fork to the branch you ask for. (1.12.2 in this case)
- 4: If you want to make changes to the merge request. Edit your fork, the merge request will auto update.

(You have done step 1)

**Comment by rtxyd** [comment]
Thanks! Last question, What if I want to change my fork name? I don't find a "change name" button. Internet didn't give me a understandable answer.

**Comment by Speiger** [comment]
@rtxyd under settings in your fork there is a section called "Repository Name"

**Comment by Speiger** [comment]
I will leave this open for a bit until you think you are fully done.
Just in case you think of something.

**Comment by rtxyd** [comment]
OK...but actually I mean, the name like "patch-1" rather than "Repository Name".

**Comment by Speiger** [comment]
"Patch-1" comes because you clicked "edit file" on our repository.
To actually use your "repo" you have to go to your repo and make a pullrequest from there.
(If you have the changes in your repo)
https://github.com/TinyModularThings/UniqueEnchantments/compare/1.12.2...rtxyd:1.12.2

Then this last "new" pull request uses your repository instead of this "edit file" patch.

**Comment by rtxyd** [comment]
All right, I learned. I will make a new pull request from rtxyd:1.12.2. Thank you very much.

**Pull request closed without merging**
